"""Quality-gated historical business cases for executional RAG.

Admission requires a documented mechanism, observable outcome, transferable
action, and a stated limit. Famous-company anecdotes without those four parts
belong in the research index, not here.
"""

INDEX = "archives/business-knowledge/research/HISTORICAL_BUSINESS_CASES_INDEX.md"


HISTORICAL_BUSINESS_CASES = [
    {
        "slug": "bk110-buffer-hiring-ahead-of-verified-revenue",
        "title": "Buffer: do not convert an optimistic revenue forecast into fixed hiring",
        "source_type": "primary_founder_postmortem",
        "trust_level": "medium",
        "domains": ["manager_coo", "finance"],
        "agent_targets": ["manager_coo", "finance_agent"],
        "tags": ["hiring", "runway", "forecast", "layoffs", "buffer", "growth_stage"],
        "source_url": "https://buffer.com/resources/layoffs-and-moving-forward/",
        "local_file": "archives/business-knowledge/research/business_cases/small_mid/buffer_2016_layoff_postmortem.html",
        "situation": "Buffer's 2016 founder postmortem reports ten layoffs, about 11% of its team, after hiring and spending moved ahead of realised revenue growth.",
        "decision_pressure": "Leaders fear delayed hiring will constrain growth, while an optimistic base case makes recurring headcount look affordable.",
        "mistake_or_risk": "A founder account is not independent proof, and hiring before demand is not always wrong. The failure mechanism is committing recurring cost without downside runway, forecast-error triggers, or staged release.",
        "recommended_next_action": "Approve hiring in tranches tied to realised revenue, margin, workload and runway; maintain a downside case; define a hiring-pause trigger before cash pressure forces abrupt layoffs; name the final cost owner.",
        "evidence_needed": ["Realised versus forecast revenue and margin", "Loaded cost and time-to-productivity", "Base and downside runway", "Bottleneck evidence for the role", "Pause and correction triggers"],
        "red_flags": ["Hiring depends on the next fundraise", "Only the optimistic case funds payroll", "Headcount is treated as a growth metric", "No owner can pause hiring"],
        "agent_lesson": "Finance owns forecast and runway depth; the Manager releases fixed cost only when evidence and downside capacity support it.",
        "hard_gate_candidate": "Material recurring hires require loaded cost, downside runway, realised-demand evidence and a pause trigger.",
        "retrieval_triggers": ["hire ahead of growth", "headcount plan", "runway before hiring", "revenue forecast missed", "avoid layoffs"],
    },
    {
        "slug": "bk111-zerodha-constraint-led-trust-growth",
        "title": "Zerodha: constraint-led growth can compound trust when customer economics work",
        "source_type": "primary_company_philosophy",
        "trust_level": "medium",
        "domains": ["sales", "marketing", "finance", "manager_coo"],
        "agent_targets": ["sales_agent", "marketing_agent", "finance_agent", "manager_coo"],
        "tags": ["bootstrapping", "word_of_mouth", "trust", "zerodha", "incentives", "india"],
        "source_url": "https://zerodha.com/about/philosophy",
        "local_file": "archives/business-knowledge/research/business_cases/india/zerodha_business_philosophy.html",
        "situation": "Zerodha describes a profitable, bootstrapped operating philosophy centred on product utility, customer-interest constraints and word of mouth rather than advertising and metric-based growth targets.",
        "decision_pressure": "Competitors' paid acquisition and sales targets make visible growth activity tempting even when it may weaken trust or unit economics.",
        "mistake_or_risk": "This is self-reported evidence from a regulated brokerage with distinctive conditions. It does not prove that advertising, targets or outside capital are inherently harmful.",
        "recommended_next_action": "Test contribution, retention, referral propensity and organic capacity; remove incentives that reward unsuitable customer actions; run bounded paid experiments only where incremental profitable reach preserves the promise.",
        "evidence_needed": ["Contribution and retention by source", "Referral rate and customer reasons", "Customer-harm risk from incentives", "Organic capacity versus opportunity window", "Incremental paid-channel lift"],
        "red_flags": ["Organic growth is praised but unmeasured", "Trust excuses a weak product", "Incentives oppose customer interest", "A no-advertising philosophy is copied without category evidence"],
        "agent_lesson": "Sales and Marketing design channels, Finance validates economics, and the Manager protects customer-interest boundaries without copying founder philosophy as universal law.",
        "hard_gate_candidate": "A channel philosophy requires contribution, retention, referral, capacity and customer-harm evidence before becoming policy.",
        "retrieval_triggers": ["grow without advertising", "word of mouth strategy", "Zerodha growth", "bootstrapped sales", "customer interest incentives"],
    },
    {
        "slug": "bk112-gomechanic-independent-financial-truth",
        "title": "GoMechanic: growth does not excuse numbers that cannot survive verification",
        "source_type": "founder_admission_investor_statement_and_reported_investigation",
        "trust_level": "high",
        "domains": ["finance", "compliance", "manager_coo"],
        "agent_targets": ["finance_agent", "compliance_agent", "manager_coo"],
        "tags": ["financial_reporting", "revenue_quality", "due_diligence", "gomechanic", "india", "governance"],
        "source_url": "https://theprint.in/india/investors-of-indias-gomechanic-seek-audit-into-inflated-financials/1322954/",
        "local_file": INDEX,
        "situation": "During fundraising, GoMechanic investors said founders misstated facts including revenue and appointed an investigator; a founder acknowledged errors, followed by major layoffs and a distressed acquisition.",
        "decision_pressure": "Valuation and fundraising deadlines can make unaudited management reporting feel like an acceptable bridge.",
        "mistake_or_risk": "Do not diagnose fraud from a variance or use reporting for legal conclusions. The transferable failure is weak separation between growth ownership, financial truth and independent assurance.",
        "recommended_next_action": "Define recognition and cut-off; reconcile contracts, invoices, delivery, collections, bank and tax records; give Finance independent authority; investigate unexplained gaps and correct numbers before financing decisions.",
        "evidence_needed": ["Customer-level ledger and policy", "Contracts, delivery and collections", "Bank, GST and statutory reconciliation", "Related parties and manual journals", "Independent investigation and remediation"],
        "red_flags": ["Fundraising numbers bypass Finance", "Revenue grows without collections or tax evidence", "Management and statutory reports do not reconcile", "Pressure to recognise incomplete work"],
        "agent_lesson": "Finance and Compliance own verification; the Manager protects their independence from teams rewarded for growth.",
        "hard_gate_candidate": "Financing and acquisition decisions require reconciled revenue, cash and tax evidence plus independent sign-off on material adjustments.",
        "retrieval_triggers": ["inflated revenue", "fundraising due diligence", "management accounts unreliable", "GoMechanic", "financial reporting investigation"],
    },
    {
        "slug": "bk113-good-glamm-integration-capacity",
        "title": "Good Glamm: acquisition momentum becomes a trap when integration and cash gates lag",
        "source_type": "founder_interview_and_business_reporting",
        "trust_level": "medium",
        "domains": ["manager_coo", "finance", "marketing"],
        "agent_targets": ["manager_coo", "finance_agent", "marketing_agent"],
        "tags": ["acquisition", "integration", "cashflow", "good_glamm", "portfolio", "india"],
        "source_url": "https://www.business-standard.com/companies/start-ups/beauty-unicorn-ceo-blames-strategy-collapse-125080101574_1.html",
        "local_file": INDEX,
        "situation": "Good Glamm assembled eleven acquisitions; its founder later described moving too much, too fast and too big, while reporting documented restructuring, delayed payments and distressed asset sales.",
        "decision_pressure": "Capital, deal momentum and a platform narrative reward closing the next acquisition before earlier businesses share systems, cash discipline or a coherent proposition.",
        "mistake_or_risk": "Acquisitions are not inherently unsound and later distress rarely has one cause. The usable mechanism is deal pace exceeding integration capacity and depending on future funding.",
        "recommended_next_action": "Quantify standalone and integration cash, name an owner, define 30/90/180-day milestones, cap concurrent integrations, protect payroll and vendors, and stop new deals when prior milestones miss.",
        "evidence_needed": ["Standalone and consolidated runway", "Measured synergy thesis", "Integration owner and capacity", "Working-capital and debt obligations", "Brand overlap and channel conflict"],
        "red_flags": ["Deal depends on the next fundraise", "No integration owner", "Payroll or vendors fund expansion", "Synergy has no baseline or deadline"],
        "agent_lesson": "Finance owns cash depth, Marketing owns portfolio coherence, and the Manager gates deal pace to integration capacity.",
        "hard_gate_candidate": "No new acquisition while existing integrations miss material cash, customer, data or operating milestones without a recovery plan.",
        "retrieval_triggers": ["too many acquisitions", "integration capacity", "house of brands failure", "Good Glamm", "acquisition cashflow"],
    },
    {
        "slug": "bk114-dominos-product-truth-before-campaign",
        "title": "Domino's: truth-telling works only when product and operations change first",
        "source_type": "company_annual_report_and_campaign_case",
        "trust_level": "high",
        "domains": ["marketing", "sales", "manager_coo"],
        "agent_targets": ["marketing_agent", "sales_agent", "manager_coo"],
        "tags": ["product", "positioning", "campaign", "dominos", "feedback", "operations"],
        "source_url": "https://ir.dominos.com/static-files/9a709686-fd64-451a-86b5-8ce23511a49a",
        "local_file": "archives/business-knowledge/research/business_cases/turnarounds/dominos_2010_annual_report.pdf",
        "situation": "Domino's used harsh customer criticism while relaunching its recipe. Its 2010 annual report connects strong US same-store sales with the improved product, advertising and operational execution.",
        "decision_pressure": "A bold confession or viral creative looks like the lever, so a business may amplify criticism before fixing the experience.",
        "mistake_or_risk": "Do not infer causality from the campaign alone or imitate self-criticism as theatre. The intervention bundled product, message and operations.",
        "recommended_next_action": "Turn recurring criticism into a tested product change; prepare delivery consistency and recovery; communicate the problem, verifiable change and retry invitation; measure repeat and complaint outcomes, not reach alone.",
        "evidence_needed": ["Structured criticism by segment", "Before/after product test", "Delivery and recovery readiness", "Trial, repeat and complaint outcomes", "Incremental effect beyond discounts"],
        "red_flags": ["Campaign precedes the fix", "Attention is the only success measure", "Operations cannot prove the promise", "Discount trial is confused with retention"],
        "agent_lesson": "Marketing owns evidence-backed repositioning, Sales closes the retry loop, and the Manager verifies that operations substantiate the promise.",
        "hard_gate_candidate": "A reputation reset requires a verified product change, delivery readiness and repeat/complaint measurement.",
        "retrieval_triggers": ["product relaunch campaign", "admit product was bad", "Dominos turnaround", "customer criticism marketing", "brand trust recovery"],
    },
    {
        "slug": "bk115-starbucks-pause-to-restore-standard",
        "title": "Starbucks: pause throughput when growth has diluted the service standard",
        "source_type": "primary_company_transformation_memo",
        "trust_level": "high",
        "domains": ["manager_coo", "marketing", "sales"],
        "agent_targets": ["manager_coo", "marketing_agent", "sales_agent"],
        "tags": ["service_quality", "training", "standard", "starbucks", "turnaround", "growth"],
        "source_url": "https://archive.starbucks.com/uploads/2018/12/4f-transformation-memos-transformation-agenda-communication-6-2008-feb-11-final.pdf",
        "local_file": INDEX,
        "situation": "As rapid expansion weakened its intended experience, Starbucks closed roughly 7,100 US company stores for several hours of espresso training for more than 135,000 people and separately closed weak locations.",
        "decision_pressure": "Stopping revenue feels costlier than adding training around live operations even when staff cannot safely practise the standard there.",
        "mistake_or_risk": "Do not copy a visible closure when the root cause differs or treat training as the whole turnaround. The mechanism is protecting a critical standard with practice, verification and structural correction.",
        "recommended_next_action": "Identify critical behaviours, observe variance, pause throughput where needed for practice, certify performance, fix staffing/process/equipment causes, and monitor customer and operating outcomes after restart.",
        "evidence_needed": ["Critical standard and variance", "Skill versus system root cause", "Pause cost versus continued harm", "Practice and certification method", "Post-restart quality and repeat measures"],
        "red_flags": ["Training substitutes for process repair", "Closure is publicity theatre", "No observed certification", "Growth resumes before standards recover"],
        "agent_lesson": "Specialists define customer and service measures; the Manager may accept a bounded revenue pause to restore a business-critical standard.",
        "hard_gate_candidate": "A materially unreliable critical standard requires containment, root-cause correction and verified restart criteria.",
        "retrieval_triggers": ["service quality declined with growth", "close for training", "Starbucks turnaround", "restore standards", "pause sales for quality"],
    },
    {
        "slug": "bk116-adobe-cannibalize-with-transition-metrics",
        "title": "Adobe: manage deliberate cannibalisation with transition metrics, not legacy revenue",
        "source_type": "primary_company_filings",
        "trust_level": "high",
        "domains": ["manager_coo", "finance", "sales", "marketing"],
        "agent_targets": ["manager_coo", "finance_agent", "sales_agent", "marketing_agent"],
        "tags": ["subscription", "business_model", "cannibalization", "adobe", "arr", "transition"],
        "source_url": "https://www.adobe.com/content/dam/cc/en/investor-relations/pdfs/ADBE-10K-FY12-FINAL.pdf",
        "local_file": "archives/business-knowledge/research/business_cases/turnarounds/adobe_fy2012_10k.pdf",
        "situation": "Adobe moved creative products from perpetual licences toward Creative Cloud subscriptions, accepting different revenue timing while tracking subscriptions and recurring revenue; by FY2015 it called perpetual creative revenue immaterial.",
        "decision_pressure": "The legacy model reports more upfront revenue, so teams defend it even when durable customer and competitive economics favour recurring delivery.",
        "mistake_or_risk": "Not every product should be a subscription, and revenue across models is not comparable without timing adjustments. Adobe's product and brand conditions may not transfer.",
        "recommended_next_action": "Model old/new cohort cash flow, retention, acquisition and support; define conversion, recurring revenue, churn, usage and runway milestones; segment migration; protect continuity; explicitly authorise cannibalisation.",
        "evidence_needed": ["Customer problem improved by model", "Old/new cohort cash contribution", "Conversion, retention, churn and usage", "Revenue and cash timing", "Migration support and downside runway"],
        "red_flags": ["Subscription serves valuation optics only", "No continuing customer value", "Legacy falls before retention is visible", "Bookings rise while activation weakens"],
        "agent_lesson": "Finance owns transition economics, Sales and Marketing own migration, and the Manager judges durable customer and cash value rather than legacy optics.",
        "hard_gate_candidate": "Business-model migration requires cohort economics, an accounting/cash bridge, customer continuity and stop/adjust triggers.",
        "retrieval_triggers": ["move to subscription", "cannibalize legacy revenue", "Adobe transition", "ARR transition metrics", "license migration"],
    },
    {
        "slug": "bk117-netflix-right-destination-wrong-migration",
        "title": "Netflix Qwikster: a correct destination can fail through customer-hostile migration",
        "source_type": "primary_company_investor_material",
        "trust_level": "high",
        "domains": ["manager_coo", "marketing", "sales"],
        "agent_targets": ["manager_coo", "marketing_agent", "sales_agent"],
        "tags": ["migration", "customer_trust", "qwikster", "netflix", "pricing", "change"],
        "source_url": "https://s22.q4cdn.com/959853165/files/doc_financials/quarterly_reports/2011/q4/Investor-Letter-Q4-2011.pdf",
        "local_file": "archives/business-knowledge/research/business_cases/failures/netflix_q4_2011_investor_letter.pdf",
        "situation": "Netflix's move toward streaming was defensible, but its 2011 price and Qwikster separation created friction and became a symbol of not listening. It reversed Qwikster after negative domestic net additions.",
        "decision_pressure": "Leaders convinced about the destination may treat brand, account continuity, pricing sequence and workflow as execution details.",
        "mistake_or_risk": "Customer backlash does not prove the strategic destination was wrong, and not all subscriber movement can be attributed to Qwikster. Separate strategy from migration design.",
        "recommended_next_action": "Map customer discontinuities; test price, brand, account and billing changes separately; preserve continuity; stage cohorts; monitor cancellation reasons and support load; enable component-level rollback.",
        "evidence_needed": ["Strategic case independent of migration", "Before/after customer journey", "Cohort cancellations and reasons", "Support and billing load", "Rollback boundaries and retained learning"],
        "red_flags": ["Multiple painful changes launch together", "Internal structure dictates experience", "Rollback equals abandoning strategy", "Objections are dismissed as resistance"],
        "agent_lesson": "Sales and Marketing own customer continuity; the Manager keeps strategic direction and migration execution as separate decisions.",
        "hard_gate_candidate": "Material migrations require staged cohorts, continuity, cancellation evidence and component-level rollback.",
        "retrieval_triggers": ["Qwikster failure", "right strategy bad execution", "migration backlash", "price change churn", "separate brand migration"],
    },
    {
        "slug": "bk118-target-canada-scale-after-canary",
        "title": "Target Canada: scale only after data, replenishment and promise work end to end",
        "source_type": "primary_company_reporting_and_investigative_reporting",
        "trust_level": "high",
        "domains": ["manager_coo", "finance", "sales", "marketing"],
        "agent_targets": ["manager_coo", "finance_agent", "sales_agent", "marketing_agent"],
        "tags": ["scale", "canary", "master_data", "supply_chain", "target_canada", "localization"],
        "source_url": "https://corporate.target.com/press/release/2015/01/target-corporation-announces-plans-to-discontinue-canadian-operations",
        "local_file": "archives/business-knowledge/research/business_cases/failures/target_2014_annual_report.pdf",
        "situation": "Target opened 133 Canadian stores rapidly amid inventory, data, system, training, price and assortment problems, then exited after deciding profitability was years away and estimating a large loss.",
        "decision_pressure": "Leases, launch schedules and scale economics encourage opening the network before one representative flow works from item setup through shelf and purchase.",
        "mistake_or_risk": "Do not reduce a multi-cause failure to software or assume a foreign proposition transfers unchanged. The mechanism is scale before verified end-to-end readiness and local fit.",
        "recommended_next_action": "Run a real canary through item, supplier, order, receipt, replenishment, price, return and customer; set accuracy/availability thresholds; expand only after representative sites survive normal and exception cycles.",
        "evidence_needed": ["Master-data accuracy and owner", "Forecast-to-shelf exceptions", "Shelf versus warehouse availability", "Local price and assortment research", "Readiness and unit economics", "Stage-gate evidence"],
        "red_flags": ["Launch date cannot move", "Full warehouse but empty shelves", "Data cleanup follows scale", "Foreign-market fit is assumed"],
        "agent_lesson": "Specialists own data, customer and economics evidence; the Manager refuses network scale until a representative canary survives exceptions.",
        "hard_gate_candidate": "Multi-site or multi-market rollout requires a real canary meeting data, availability, customer-fit and unit-economics thresholds.",
        "retrieval_triggers": ["Target Canada failure", "scale too fast", "empty shelves full warehouse", "master data rollout", "expansion canary"],
    },
    {
        "slug": "bk119-wework-duration-mismatch-governance",
        "title": "WeWork: flexible revenue cannot safely fund rigid obligations without controls",
        "source_type": "regulatory_filing_and_bankruptcy_reporting",
        "trust_level": "high",
        "domains": ["finance", "manager_coo"],
        "agent_targets": ["finance_agent", "manager_coo"],
        "tags": ["duration_mismatch", "fixed_cost", "liquidity", "wework", "governance", "growth"],
        "source_url": "https://www.sec.gov/Archives/edgar/data/1533523/000162827919000125/filename1.htm",
        "local_file": INDEX,
        "situation": "WeWork expanded through long leases while selling comparatively flexible memberships, accumulated losses and disclosed related-party issues; its 2019 IPO failed and it later entered bankruptcy.",
        "decision_pressure": "Footprint and revenue growth are visible while long obligations, volatile demand and conflicts sit outside the headline metric.",
        "mistake_or_risk": "Coworking is not inherently unviable and bankruptcy had multiple causes. Transfer duration/liquidity mismatch, fixed commitments before proven unit economics, and conflict governance.",
        "recommended_next_action": "Match duration and repricing rights; stress occupancy and churn; map obligations by month; cap expansion by downside liquidity and mature-site economics; require independent related-party approval.",
        "evidence_needed": ["Customer duration and churn", "Lease/debt obligations and breaks", "Mature-unit contribution and payback", "Downside liquidity stress", "Related-party register and approvals"],
        "red_flags": ["Cancellable revenue funds non-cancellable cost", "Growth requires continuous funding", "New units hide weak mature units", "Founder transactions lack independent review"],
        "agent_lesson": "Finance owns duration and liquidity; the Manager gates growth and enforces governance instead of treating fundraising as model proof.",
        "hard_gate_candidate": "Long fixed obligations require duration analysis, downside liquidity, mature-unit economics and related-party clearance.",
        "retrieval_triggers": ["WeWork failure", "long lease short membership", "duration mismatch", "fixed obligations growth", "related party founder"],
    },
    {
        "slug": "bk120-svb-concentration-duration-liquidity",
        "title": "SVB: rapid growth can hide concentration and duration risk until confidence breaks",
        "source_type": "official_regulatory_postmortem",
        "trust_level": "authoritative",
        "domains": ["finance", "manager_coo"],
        "agent_targets": ["finance_agent", "manager_coo"],
        "tags": ["concentration", "liquidity", "duration", "svb", "stress_test", "funding"],
        "source_url": "https://www.federalreserve.gov/publications/review-of-the-federal-reserves-supervision-and-regulation-of-silicon-valley-bank.htm",
        "local_file": "archives/business-knowledge/research/business_cases/failures/federal_reserve_svb_review_2023.pdf",
        "situation": "The Federal Reserve found SVB grew rapidly with concentrated, largely uninsured deposits and inadequate interest-rate and liquidity management; a connected depositor base then withdrew at extraordinary speed.",
        "decision_pressure": "Growth and stable recent behaviour make concentrated funding and long-duration assets look cheaper than resilience.",
        "mistake_or_risk": "Do not transplant bank ratios into an SMB. Transfer the concentration, maturity and correlated-behaviour logic.",
        "recommended_next_action": "Map customer, supplier, lender, bank and funding concentrations; identify parties likely to act together; time inflows against fixed outflows; stress sudden loss; pre-arrange diversified liquidity and triggers.",
        "evidence_needed": ["Revenue and funding concentration", "Contract and cash timing", "Correlated-party behaviour", "Immediate cash under stress", "Backup liquidity and activation owner"],
        "red_flags": ["One ecosystem controls most inflow", "Callable cash funds long commitments", "Assumptions are weakened to pass", "Growth outpaces risk capacity"],
        "agent_lesson": "Finance performs concentration and liquidity depth; the Manager acts on severe plausible scenarios before the probability feels comfortable.",
        "hard_gate_candidate": "Material concentration or duration mismatch requires correlated-loss stress, backup liquidity and activation triggers.",
        "retrieval_triggers": ["customer concentration", "funding concentration", "SVB lesson", "duration liquidity mismatch", "correlated customer loss"],
    },
    {
        "slug": "bk121-southwest-recovery-is-product-capacity",
        "title": "Southwest: capacity includes recovery, communication and refunds—not only throughput",
        "source_type": "official_enforcement_postmortem",
        "trust_level": "authoritative",
        "domains": ["manager_coo", "finance", "sales"],
        "agent_targets": ["manager_coo", "finance_agent", "sales_agent"],
        "tags": ["resilience", "recovery", "southwest", "communication", "refunds", "operations"],
        "source_url": "https://www.transportation.gov/briefing-room/dot-penalizes-southwest-airlines-140-million-2022-holiday-meltdown",
        "local_file": INDEX,
        "situation": "Winter weather triggered Southwest's 2022 disruption, but recovery, notification, refund and reimbursement failed at scale. US DOT action covered more than two million passengers and a $140 million settlement.",
        "decision_pressure": "Normal-day utilisation rewards lean recovery staffing and fragile fallbacks because contingency capacity looks idle.",
        "mistake_or_risk": "Do not label every disruption a technology failure or let the external trigger excuse preventable recovery harm. Separate prevention, containment, recovery and remedy.",
        "recommended_next_action": "Model peak disruption; test degraded scheduling and manual authority; reserve recovery/communication capacity; predefine refund/remedy workflows; exercise through full backlog clearance.",
        "evidence_needed": ["Dependency and disruption scenarios", "Recovery throughput versus backlog", "Fallback data, staffing and authority", "Notification and remedy timing", "Exercise through backlog clearance"],
        "red_flags": ["Continuity test stops at restoration", "Fallback cannot reconcile operations", "Support is excluded from resilience", "No remedy authority during disruption"],
        "agent_lesson": "Operations and Sales protect recovery and remedy, Finance funds severe-event capacity, and the Manager treats recovery as part of the promise.",
        "hard_gate_candidate": "Critical operations require tested degraded mode, backlog-clearance capacity, communication and remedy authority.",
        "retrieval_triggers": ["Southwest meltdown", "recovery failure", "continuity backlog", "refund during outage", "recovery capacity"],
    },
    {
        "slug": "bk122-wells-fargo-warning-patterns",
        "title": "Wells Fargo: complaints and repeated terminations are system-level control evidence",
        "source_type": "official_enforcement_and_independent_board_findings",
        "trust_level": "authoritative",
        "domains": ["sales", "compliance", "finance", "manager_coo"],
        "agent_targets": ["sales_agent", "compliance_agent", "finance_agent", "manager_coo"],
        "tags": ["sales_incentives", "consent", "complaints", "wells_fargo", "conduct", "governance"],
        "source_url": "https://www.consumerfinance.gov/archive/newsroom/consumer-financial-protection-bureau-fines-wells-fargo-100-million-widespread-illegal-practice-secretly-opening-unauthorized-accounts/",
        "local_file": "archives/business-knowledge/research/business_cases/compliance/cfpb_wells_fargo_2016_enforcement.html",
        "situation": "Wells Fargo used aggressive cross-sell goals while employees opened unauthorised accounts. Enforcement and board findings showed complaints, terminations and escalation failures before full consequences were accepted.",
        "decision_pressure": "Leaders can call misconduct isolated because the headline metric is strong and cases are dispersed across complaints, refunds, terminations and locations.",
        "mistake_or_risk": "An ambitious target is not proof of misconduct, and firing frontline staff is not system remediation. The mechanism combines incentive design, warning aggregation, consent proof and leadership response.",
        "recommended_next_action": "Verify customer consent and beneficial use; aggregate complaints, reversals, refunds and conduct cases by leader/channel; test gaming paths; give Compliance escalation access; hold leaders accountable for pattern response.",
        "evidence_needed": ["Customer consent and beneficial use", "Complaints, reversals and refunds", "Conduct cases by manager and pressure", "Gaming analysis and counter-metrics", "Escalation and leader response"],
        "red_flags": ["Sales and complaints rise together", "Many people are fired for one behaviour", "Controls report through Sales", "Consent is inferred from employee action"],
        "agent_lesson": "Sales owns customer value, Compliance owns assurance, Finance checks reversals, and the Manager treats dispersed warnings as system evidence.",
        "hard_gate_candidate": "Incentivised customer actions require consent proof, outcome checks, pattern monitoring and independent escalation.",
        "retrieval_triggers": ["unauthorized accounts", "sales target misconduct", "complaints warning signal", "Wells Fargo scandal", "customer consent controls"],
    },
]
